apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-operator
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redis-operator-clusterrole
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec", "pods/log", "services", "endpoints", "persistentvolumeclaims", "events"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["database.example.com"]
  resources: ["redises"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch", "create", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: redis-operator-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: redis-operator
  namespace: default
roleRef:
  kind: ClusterRole
  name: redis-operator-clusterrole
  apiGroup: rbac.authorization.k8s.io

