# redis-crd.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: redises.database.example.com
spec:
  group: database.example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                masterSize: 
                  type: integer
                  default: 1
                slaveSize:
                  type: integer
                  default: 2
                image:
                  type: string
                  default: "redis:latest"
                backupEnabled:
                  type: boolean
                  default: false
                backupSchedule:
                  type: string
                persistentVolumeSize:
                  type: string
                  default: "1Gi"
            status:
              type: object
              properties:
                nodes:
                  type: array
                  items:
                    type: string
  scope: Namespaced
  names:
    plural: redises
    singular: redis
    kind: Redis
    shortNames:
      - rd
